//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhenThuong_KyLuat
    {
        public string SoQuyetDinh { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<int> CREATE0_BY { get; set; }
        public Nullable<System.DateTime> CREATE0_DATE { get; set; }
        public Nullable<int> UPDATEO_BY { get; set; }
        public Nullable<System.DateTime> UPDATEO_DATE { get; set; }
        public Nullable<int> DELETEO_BY { get; set; }
        public Nullable<System.DateTime> DELETEO_DATE { get; set; }
    
        public virtual T_NhanVien T_NhanVien { get; set; }
    }
}
