//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bang_Luong
    {
        public int ID { get; set; }
        public Nullable<int> MakyCong { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> NgayCongTrongThang { get; set; }
        public Nullable<double> NgayPhep { get; set; }
        public Nullable<double> KhongPhep { get; set; }
        public Nullable<double> NgayLe { get; set; }
        public Nullable<double> NgayChuNhat { get; set; }
        public Nullable<double> TangCa { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public Nullable<double> NgayThuong { get; set; }
        public Nullable<double> UngLuong { get; set; }
        public Nullable<double> ThucLanh { get; set; }
        public Nullable<int> CREATEO_BY { get; set; }
        public Nullable<System.DateTime> CREATEO_DATE { get; set; }
        public Nullable<int> UPDATEO_BY { get; set; }
        public Nullable<System.DateTime> UPDATEO_DATE { get; set; }
        public Nullable<int> DELETEO_BY { get; set; }
        public Nullable<System.DateTime> DELETEO_DATE { get; set; }
    }
}
