//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BangCong
    {
        public int id_BangCong { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<int> GioVao { get; set; }
        public Nullable<int> PhutVao { get; set; }
        public Nullable<int> GioRa { get; set; }
        public Nullable<int> PhutRa { get; set; }
        public Nullable<int> id_NhanVIen { get; set; }
        public Nullable<int> id_LoaiCong { get; set; }
    
        public virtual T_LoaiCong T_LoaiCong { get; set; }
        public virtual T_NhanVien T_NhanVien { get; set; }
    }
}
