//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BangCong_NVien_ChiTiet
    {
        public int ID { get; set; }
        public Nullable<int> MaKyCong { get; set; }
        public Nullable<int> id_NoiLV { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Thu { get; set; }
        public string GioVao { get; set; }
        public string GioRa { get; set; }
        public Nullable<double> NgayPhep { get; set; }
        public Nullable<double> CongNgayLe { get; set; }
        public Nullable<double> CongChuNhat { get; set; }
        public Nullable<double> NghiKhongPhep { get; set; }
        public Nullable<double> NgayCong { get; set; }
        public string KyHieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> CREATEO_BY { get; set; }
        public Nullable<System.DateTime> CREATEO_DATE { get; set; }
        public Nullable<int> UPDATEO_BY { get; set; }
        public Nullable<System.DateTime> UPDATEO_DATE { get; set; }
    }
}
