//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BaoHiem
    {
        public int id_BaoHiem { get; set; }
        public string So_BaoHiem { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string Noi_DK_Kham_Benh { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
    
        public virtual T_NhanVien T_NhanVien { get; set; }
    }
}
