//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DieuChuyen
    {
        public string SoDieuChuyen { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
        public Nullable<int> id_PhongBan { get; set; }
        public Nullable<int> id_PhongBan2 { get; set; }
        public string LiDo { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> CREATEO_BY { get; set; }
        public Nullable<System.DateTime> CREATEO_DATE { get; set; }
        public Nullable<int> UPDATEO_BY { get; set; }
        public Nullable<System.DateTime> UPDATEO_DATE { get; set; }
        public Nullable<int> DELETEO_BY { get; set; }
        public Nullable<System.DateTime> DELETEO_DATE { get; set; }
    
        public virtual T_NhanVien T_NhanVien { get; set; }
        public virtual T_PhongBan T_PhongBan { get; set; }
    }
}
