//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_HopDong()
        {
            this.T_NhanVien_NangLuong = new HashSet<T_NhanVien_NangLuong>();
        }
    
        public string So_HopDong { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<int> Lanky { get; set; }
        public string ThoiHan { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
        public Nullable<int> id_NoiLV { get; set; }
        public Nullable<int> DELETE_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> CREATEO_BY { get; set; }
        public Nullable<System.DateTime> CREATEO_DATE { get; set; }
    
        public virtual T_NhanVien T_NhanVien { get; set; }
        public virtual T_NoiLamViec T_NoiLamViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_NhanVien_NangLuong> T_NhanVien_NangLuong { get; set; }
    }
}
