//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LichLV
    {
        public int id_LichLamViec { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
        public Nullable<int> id_NoiLV { get; set; }
        public Nullable<int> id_Khoa { get; set; }
        public Nullable<int> id_KhoaDay { get; set; }
        public Nullable<int> id_LopDay { get; set; }
        public Nullable<int> id_MonDay { get; set; }
        public Nullable<int> id_PhongHoc { get; set; }
        public Nullable<int> SoTin { get; set; }
        public Nullable<System.DateTime> ThoiGianBD { get; set; }
        public Nullable<System.DateTime> ThoiGianKT { get; set; }
        public Nullable<int> id_LoaiCa { get; set; }
        public Nullable<int> CREATEO_BY { get; set; }
        public Nullable<System.DateTime> CREATEO_DATE { get; set; }
        public Nullable<int> UPDATEO_BY { get; set; }
        public Nullable<System.DateTime> UPDATEO_DATE { get; set; }
        public Nullable<int> DELETEO_BY { get; set; }
        public Nullable<System.DateTime> DELETEO_DATE { get; set; }
    
        public virtual T_Khoa T_Khoa { get; set; }
        public virtual T_KhoaDay T_KhoaDay { get; set; }
        public virtual T_LoaiCa T_LoaiCa { get; set; }
        public virtual T_LopDay T_LopDay { get; set; }
        public virtual T_MonDay T_MonDay { get; set; }
        public virtual T_NhanVien T_NhanVien { get; set; }
        public virtual T_NoiLamViec T_NoiLamViec { get; set; }
        public virtual T_PhongHoc T_PhongHoc { get; set; }
    }
}
