//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_NhanVien_NangLuong
    {
        public string SQDNL { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
        public string So_HopDong { get; set; }
        public Nullable<double> HeSoLuongHT { get; set; }
        public Nullable<double> HSLuongMoi { get; set; }
        public Nullable<System.DateTime> NgayLenLuong { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> CREATEO_BY { get; set; }
        public Nullable<System.DateTime> CREATEO_DATE { get; set; }
        public Nullable<int> UPDATEO_BY { get; set; }
        public Nullable<System.DateTime> UPDATEO_DATE { get; set; }
        public Nullable<int> DELETEO_BY { get; set; }
        public Nullable<System.DateTime> DELETEO_DATE { get; set; }
    
        public virtual T_HopDong T_HopDong { get; set; }
        public virtual T_NhanVien T_NhanVien { get; set; }
    }
}
