//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_NhanVien()
        {
            this.KhenThuong_KyLuat = new HashSet<KhenThuong_KyLuat>();
            this.T_BangCong = new HashSet<T_BangCong>();
            this.T_BaoHiem = new HashSet<T_BaoHiem>();
            this.T_DieuChuyen = new HashSet<T_DieuChuyen>();
            this.T_HopDong = new HashSet<T_HopDong>();
            this.T_LichLV = new HashSet<T_LichLV>();
            this.T_NhanVien_NangLuong = new HashSet<T_NhanVien_NangLuong>();
            this.T_NhanVienPhuCap = new HashSet<T_NhanVienPhuCap>();
            this.T_TangCa = new HashSet<T_TangCa>();
            this.T_THOIVIEC = new HashSet<T_THOIVIEC>();
            this.T_UngLuong = new HashSet<T_UngLuong>();
        }
    
        public int id_NhanVien { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string CCCD { get; set; }
        public string DiaChi { get; set; }
        public byte[] HinhAnh { get; set; }
        public string PhanQuyen { get; set; }
        public Nullable<int> id_NoiLV { get; set; }
        public Nullable<int> id_PhongBan { get; set; }
        public Nullable<int> id_BoPhan { get; set; }
        public Nullable<int> id_ChucVu { get; set; }
        public Nullable<int> id_TrinhDo { get; set; }
        public Nullable<int> id_DanToc { get; set; }
        public Nullable<int> id_TonGiao { get; set; }
        public Nullable<bool> DATHOIVIEC { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhenThuong_KyLuat> KhenThuong_KyLuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BangCong> T_BangCong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BaoHiem> T_BaoHiem { get; set; }
        public virtual T_BoPhan T_BoPhan { get; set; }
        public virtual T_ChucVu T_ChucVu { get; set; }
        public virtual T_DanToc T_DanToc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DieuChuyen> T_DieuChuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HopDong> T_HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LichLV> T_LichLV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_NhanVien_NangLuong> T_NhanVien_NangLuong { get; set; }
        public virtual T_NoiLamViec T_NoiLamViec { get; set; }
        public virtual T_PhongBan T_PhongBan { get; set; }
        public virtual T_TonGiao T_TonGiao { get; set; }
        public virtual T_TrinhDo T_TrinhDo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_NhanVienPhuCap> T_NhanVienPhuCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TangCa> T_TangCa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_THOIVIEC> T_THOIVIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UngLuong> T_UngLuong { get; set; }
    }
}
