//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TangCa
    {
        public int id_TangCa { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<double> SoGioTangCa { get; set; }
        public Nullable<int> id_LoaiCa { get; set; }
        public Nullable<int> id_NhanVien { get; set; }
    
        public virtual T_LoaiCa T_LoaiCa { get; set; }
        public virtual T_NhanVien T_NhanVien { get; set; }
    }
}
